export const SIGN_IN_GOOGLE_SUCCESS = 'SIGN_IN_GOOGLE_SUCCESS';
export const SIGN_IN_GOOGLE_FAIL = 'SIGN_IN_GOOGLE_FAIL';
export const SIGN_OUT = 'SIGN_OUT';
export const GET_CHAT_LIST = 'GET_CHAT_LIST';
export const ERROR = 'ERROR';
export const CHOOSE_PEOPLE = 'CHOOSE_PEOPLE';
export const CONVERSATION = 'CONVERSATION';
export const GET_CONVERSATION = 'GET_CONVESATION';

